parameters:

    #~ Comment part
    orm.comment.author:    'Eureka Orm Generator'
    orm.comment.copyright: 'Romain Cottard'

    #~ Namespace base config
    orm.base_namespace.entity:     'Eureka\Domain\Blog'
    orm.base_namespace.mapper:     'Eureka\Domain\Blog'
    orm.base_namespace.repository: 'Eureka\Domain\Blog'

    #~ Path base config
    orm.base_path.entity:     '%kernel.directory.root%/src'
    orm.base_path.mapper:     '%kernel.directory.root%/src'
    orm.base_path.repository: '%kernel.directory.root%/src'

    #~ Cache base config
    orm.cache.prefix: 'eka.dm.blog.'

    #~ Validation
    orm.validation.enabled: true
    orm.validation.auto:    true

    orm.configs:
        #~ Core Blog
        blog_author:   '%orm.config.blog_author%'
        blog_post:     '%orm.config.blog_post%'
        blog_category: '%orm.config.blog_category%'
        blog_tag:      '%orm.config.blog_tag%'
        blog_post_tag: '%orm.config.blog_post_tag%'
