<?php

/*
 * Copyright (c) Romain Cottard
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Eureka\Domain\Blog\Infrastructure\Mapper\Abstracts;

use Eureka\Component\Orm\AbstractMapper;
use Eureka\Domain\Blog\Entity\Tag;
use Eureka\Domain\Blog\Infrastructure\Mapper\PostTagMapper;

/**
 * Abstract Tag mapper class.
 *
 * /!\ AUTO GENERATED FILE. DO NOT EDIT THIS FILE.
 * You can add your specific code in child class: {{ class.child }}
 *
 * @author Eureka Orm Generator
 */
abstract class AbstractTagMapper extends AbstractMapper
{
    /**
     * Initialize mapper with proper values for mapped table.
     *
     * @return void
     */
    protected function initialize(): void
    {
        $this->setEntityClass(Tag::class);
        $this->setTable('blog_tag');

        $this->setFields([
            'blog_tag_id',
            'blog_tag_name'
        ]);

        $this->setPrimaryKeys([
            'blog_tag_id'
        ]);

        $this->setNamesMap([
            'blog_tag_id' => [
                'get'      => 'getId',
                'set'      => 'setId',
                'property' => 'id',
            ],
            'blog_tag_name' => [
                'get'      => 'getName',
                'set'      => 'setName',
                'property' => 'name',
            ],
        ]);

        $this->setValidatorConfig([
            'blog_tag_id' => [
                'type'      => 'integer',
                'options'   => ['min_range' => 0, 'max_range' => 4294967295],
            ],
            'blog_tag_name' => [
                'type'      => 'string',
                'options'   => ['min_length' => 0, 'max_length' => 50],
            ],
        ]);

        $this->setJoinConfigs([
            'PostsTag' => [
                'mapper'   => PostTagMapper::class,
                'type'     => 'INNER',
                'relation' => 'many',
                'keys'     => ['blog_tag_id' => true],
            ],
        ]);
    }
}
