<?php

/*
 * Copyright (c) Romain Cottard
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Eureka\Domain\Blog\Infrastructure\Mapper\Abstracts;

use Eureka\Component\Orm\AbstractMapper;
use Eureka\Domain\Blog\Entity\Category;
use Eureka\Domain\Blog\Infrastructure\Mapper\PostMapper;

/**
 * Abstract Category mapper class.
 *
 * /!\ AUTO GENERATED FILE. DO NOT EDIT THIS FILE.
 * You can add your specific code in child class: {{ class.child }}
 *
 * @author Eureka Orm Generator
 */
abstract class AbstractCategoryMapper extends AbstractMapper
{
    /**
     * Initialize mapper with proper values for mapped table.
     *
     * @return void
     */
    protected function initialize(): void
    {
        $this->setEntityClass(Category::class);
        $this->setTable('blog_category');

        $this->setFields([
            'blog_category_id',
            'blog_category_name'
        ]);

        $this->setPrimaryKeys([
            'blog_category_id'
        ]);

        $this->setNamesMap([
            'blog_category_id' => [
                'get'      => 'getId',
                'set'      => 'setId',
                'property' => 'id',
            ],
            'blog_category_name' => [
                'get'      => 'getName',
                'set'      => 'setName',
                'property' => 'name',
            ],
        ]);

        $this->setValidatorConfig([
            'blog_category_id' => [
                'type'      => 'integer',
                'options'   => ['min_range' => 0, 'max_range' => 65535],
            ],
            'blog_category_name' => [
                'type'      => 'string',
                'options'   => ['min_length' => 0, 'max_length' => 50],
            ],
        ]);

        $this->setJoinConfigs([
            'Posts' => [
                'mapper'   => PostMapper::class,
                'type'     => 'LEFT OUTER',
                'relation' => 'many',
                'keys'     => ['blog_category_id' => true],
            ],
        ]);
    }
}
