<?php

/*
 * Copyright (c) Romain Cottard
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Eureka\Domain\Blog\Infrastructure\Mapper\Abstracts;

use Eureka\Component\Orm\AbstractMapper;
use Eureka\Domain\Blog\Entity\PostTag;
use Eureka\Domain\Blog\Infrastructure\Mapper\PostMapper;
use Eureka\Domain\Blog\Infrastructure\Mapper\TagMapper;

/**
 * Abstract PostTag mapper class.
 *
 * /!\ AUTO GENERATED FILE. DO NOT EDIT THIS FILE.
 * You can add your specific code in child class: {{ class.child }}
 *
 * @author Eureka Orm Generator
 */
abstract class AbstractPostTagMapper extends AbstractMapper
{
    /**
     * Initialize mapper with proper values for mapped table.
     *
     * @return void
     */
    protected function initialize(): void
    {
        $this->setEntityClass(PostTag::class);
        $this->setTable('blog_post_tag');

        $this->setFields([
            'blog_post_id',
            'blog_tag_id'
        ]);

        $this->setPrimaryKeys([
            'blog_post_id',
            'blog_tag_id'
        ]);

        $this->setNamesMap([
            'blog_post_id' => [
                'get'      => 'getBlogPostId',
                'set'      => 'setBlogPostId',
                'property' => 'blogPostId',
            ],
            'blog_tag_id' => [
                'get'      => 'getBlogTagId',
                'set'      => 'setBlogTagId',
                'property' => 'blogTagId',
            ],
        ]);

        $this->setValidatorConfig([
            'blog_post_id' => [
                'type'      => 'integer',
                'options'   => ['min_range' => 0, 'max_range' => 4294967295],
            ],
            'blog_tag_id' => [
                'type'      => 'integer',
                'options'   => ['min_range' => 0, 'max_range' => 4294967295],
            ],
        ]);

        $this->setJoinConfigs([
            'Post' => [
                'mapper'   => PostMapper::class,
                'type'     => 'INNER',
                'relation' => 'one',
                'keys'     => ['blog_post_id' => true],
            ],
            'Tag' => [
                'mapper'   => TagMapper::class,
                'type'     => 'INNER',
                'relation' => 'one',
                'keys'     => ['blog_tag_id' => true],
            ],
        ]);
    }
}
