# ORM Config file
parameters:

    orm.config.blog_category:
        comment:
            author:     '%orm.comment.author%'
            copyright:  '%orm.comment.copyright%'

        namespace:
            entity:     '%orm.base_namespace.entity%\Entity'
            mapper:     '%orm.base_namespace.mapper%\Infrastructure\Mapper'
            repository: '%orm.base_namespace.repository%\Repository'

        path:
            entity:     '%orm.base_path.entity%/Entity'
            mapper:     '%orm.base_path.mapper%/Infrastructure/Mapper'
            repository: '%orm.base_path.repository%/Repository'

        cache:
            prefix:     '%orm.cache.prefix%blog_post_tag'

        database:
            table:      'blog_category'
            prefix:     'blog_category'

        class:
            classname: 'Category'

        joins:
            Posts:
                eager_loading: true
                config:   'blog_post'
                relation: !php/const Eureka\Component\Orm\Enumerator\JoinRelation::MANY
                type:     !php/const Eureka\Component\Orm\Enumerator\JoinType::LEFT
                keys:
                    blog_category_id: true


        #~ Validation input in entities
        validation:
            enabled:             '%orm.validation.enabled%'
            auto:                '%orm.validation.auto%'
            extended_validation: ~
